# File Path: xaos/packages/frontend/docker-compose.yml
# Version: 1.2.0
#
# Description:
# Updated Docker Compose configuration for Rust backend.
# Build context now includes backend and shared folders for successful COPY.
#
# Usage Guide:
# docker compose up -d --build
# docker compose logs -f rust_backend

services:
  # =============================================================================
  # RUST BACKEND SERVICE
  # =============================================================================
  rust_backend:
    container_name: rust_backend
    build:
      context: ../.. # <-- context now includes backend/ and shared/
      dockerfile: packages/backend/Dockerfile
    ports:
      - "3010:3001"
    volumes:
      # Docker socket for container management
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Map the shared data directory
      - ./../../packages/shared:/app/shared:ro
      # Map the python scripts needed for execution
      - ./xaospy:/app/xaospy:ro
    environment:
      RUST_LOG: "debug,rust_backend=debug"
      HOST_PROJECT_ROOT: "${PROJECT_ROOT}"
    depends_on:
      - python_runner
    restart: unless-stopped
    networks:
      - vlabs-net

  # =============================================================================
  # PYTHON RUNNER SERVICE
  # =============================================================================
  python_runner:
    container_name: python_runner
    image: python-runner
    build:
      context: ./xaospy
      dockerfile: Dockerfile
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    volumes:
      # Map the python project directory
      - ./xaospy:/xaospy
      # Map the shared data directory
      - ./../../packages/shared:/shared
    ports:
      - "8001:8000"
    networks:
      - vlabs-net
    restart: unless-stopped

networks:
  vlabs-net:
    driver: bridge
