# backend/Cargo.toml
[package]
name = "rust-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web framework
axum = { version = "0.7", features = ["ws", "macros"] }
tokio = { version = "1.0", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"

# WebSocket support
futures-util = "0.3"

# UUID generation for connection IDs
uuid = { version = "1.0", features = ["v4", "serde"] }

# Date/time handling
chrono = { version = "0.4", features = ["serde"] }

# Error handling
thiserror = "1.0"

# JSON Schema
jsonschema = "0.17"

# Logging
tracing = "0.1"
tracing-subscriber = "0.3"

# File system watching (optional, for auto-reload features)
notify = { version = "6.0", optional = true }

# Additional async utilities
tokio-stream = "0.1"

[features]
default = []
file-watching = ["notify"]

[dev-dependencies]
tokio-test = "0.4"
